In [14]:
import numpy as np

# Create a 1D array from a Python list
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

# Create a 2D array from a nested Python list
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Shape of the array
print(arr_2d.shape)  # Output: (3, 3)

# Data type of the array
print(arr_2d.dtype)  # Output: int64


(3, 3)
int32


In [16]:
print(arr_1d.dtype) 

int32


In [17]:
# Element-wise addition
arr_sum = arr_1d + 10
print(arr_sum)  # Output: [11 12 13 14 15]




[11 12 13 14 15]


In [18]:
# Element-wise multiplication
arr_mul = arr_1d * 2
print(arr_mul)  # Output: [ 2  4  6  8 10]



[ 2  4  6  8 10]


In [19]:
# Matrix multiplication
mat_mul = np.dot(arr_2d, arr_1d)
print(mat_mul)  # Output: [14 32 50]

ValueError: shapes (3,3) and (5,) not aligned: 3 (dim 1) != 5 (dim 0)

In [20]:
# Accessing elements
print(arr_1d[0])    # Output: 1
print(arr_2d[1, 1])  # Output: 5

# Slicing
print(arr_1d[1:4])    # Output: [2 3 4]
print(arr_2d[:, :2])  # Output: [[1 2] [4 5] [7 8]]


1
5
[2 3 4]
[[1 2]
 [4 5]
 [7 8]]


In [21]:
# Sum of all elements
print(np.sum(arr_1d))  # Output: 15

# Mean of all elements
print(np.mean(arr_1d))  # Output: 3.0

# Standard deviation of all elements
print(np.std(arr_1d))   # Output: 1.4142135623730951


15
3.0
1.4142135623730951


## Convert Text to Audio

In [22]:
from gtts import gTTS
import os

def convert_text_to_audio(text, language='en'):
    # Create a gTTS object
    tts = gTTS(text=text, lang=language, slow=False)

    # Save the audio to a file
    tts.save("output.mp3")

    # Play the audio
    os.system("start output.mp3")

if __name__ == "__main__":
    # Text to be translated to audio
    text = "I love you Shingai bhobho my lovey wife , the mother to my daugther Makanakaishe and son Makatendeka?"
    text2 ="""This is a book about common sense from the standpoint of artificial intelligence (AI). While only a small number of AI researchers actually work on
common sense directly, the topic has been around since the beginning of
the field. AI was given its name in the 1950s by US computer scientist John
McCarthy (1927–2011),
and one of the first papers ever written about AI is
one he presented in 1958 called “Programs with Common Sense.”
With a history like this, one might think that the common sense part of
AI would be well in hand by now, more than sixty years later. But in a 2019
book called Rebooting AI, Gary Marcus and Ernest Davis make this observation:
“Unfortunately acquiring common sense is much harder than one
might think. And as we will see, the need for getting machines to acquire
common sense is also far more pervasive than one might have imagined.”
The implication here is clear: AI systems could really use some sort of
common sense, but nobody has yet figured out how to provide them with
it. And it’s not as if anyone thinks that common sense is some minor aspect
of intelligence; arguably, it’s at the very core.
What we propose to do in this book is to take a hard look at this notion
of common sense to get a better sense of what it is, why it is important,
and what it might take to make it work in an AI system. But before setting
out on this long and winding road, let us have a look at where we will be
going."""

    # Call the function to translate text to audio
    text_to_audio(text2)


gTTSError: Failed to connect. Probable cause: Unknown

In [ ]:
from gtts import gTTS

# Define the text
text = "This is a sample text to convert to audio using different language voice options "

# Define the voice (choose one from the list)
voice = "so-so-standard-A"  # American English

# Create a gTTS object
#tts = gTTS(text=text, lang="en", slow=False, tld="co.zw")
tts = gTTS(text=text, lang="en-za", slow=False)
#tts = gTTS(text=text, lang="en", slow=False, tld="com.au")
# Save the audio to a file
tts.save("output1.mp3")

# A dummy problem
We’ll start with a simple problem. Suppose we have a dataset organized in multiple files, and we want to get every word inside it.

It is a trivial problem, and it can be solved in many ways, even in fewer lines of code than I am about to show you, but hopefully, it is complex enough that you can relate to real-world projects that you worked on.

In [11]:
import os
from typing import List


all_words = []

# Get all files
folder_path = "../project_1_apis/test"
for root, dirs, files in os.walk(folder_path):
    for file in files:
        filepath = os.path.join(root, file)

        # Read all lines from the file
        with open(filepath, 'r') as f:
            lines = f.readlines()

        for line in lines:
            new_words = line.split()
            all_words.extend(new_words)

#print(all_words)
print(filepath)
#print(dirs)

../project_1_apis/test\text_5.txt


# Clean up the code
One of the lessonslearned from reading Clean Code by Robert C. Martin 
 book is that if there are commented sections of code, that is a sign that they need to be moved to separate functions.

Also, it’s better to arrange them in a top-down hierarchical view. The main function should stay at the top, then, the rest of the functions should be defined below in a Breadth-First-Search fashion.

In [13]:
import os
from typing import List


def main():
    folder_path = "data"
    filepaths = get_filepaths(folder_path) # ["/home/file1.txt", "/home/file2.txt", …]
    lines = get_lines(filepaths) # ["Lorem ipsum dolor sit amet", "Consectetur adipiscing elit", …]
    words = get_words(lines) # ["Lorem", "ipsum", "dolor sit", …]
    print(words)

def get_filepaths(dir: str) -> List[str]:
    all_filepaths = []
    for root, dirs, files in os.walk(dir):
        for file in files:
            filepath = os.path.join(root, file)
            all_filepaths.append(filepath)
    return all_filepaths

def get_lines(filepaths: List[str]) -> List[str]:
    all_lines = []
    for filepath in filepaths:
        with open(filepath, 'r') as f:
            lines = f.readlines()
            all_lines.extend(lines)
    return all_lines

def get_words(lines: List[str]) -> List[str]:
    all_words = []
    for line in lines:
        all_words.extend(line.split())
    return all_words

if __name__ == "__main__":
    main()

['["Lorem', 'ipsum', 'dolor', 'sit', 'amet",', '"Consectetur', 'adipiscing', 'elit",', '"One"', ',…]', '["Lorem', 'ipsum', 'dolor', 'sit', 'amet",', '"Consectetur', 'adipiscing', 'elit","two",', '…]', '["Lorem', 'ipsum', 'dolor', 'sit', 'amet",', '"Consectetur', 'adipiscing', 'elit","Three",', '…]', '["Lorem', 'ipsum', 'dolor', 'sit', 'amet",', '"Consectetur', 'adipiscing', 'elit","Four",', '…]', '["Lorem', 'ipsum', 'dolor', 'sit', 'amet",', '"Consectetur', 'adipiscing', 'elit",', '"Five",', '…]']
